NAME_MAX_LENGTH = 200
COLOR_MAX_LENGTH = 7
SLUG_MAX_LENGTH = 200
MEASUREMENT_UNIT_MAX_LENGTH = 200
MIN_MINUTE_VALUE = 1
MIN_AMOUNT_VALUE = 1

ADMIN_IMAGE_WIDTH = 150
ADMIN_IMAGE_HEIGHT = 150

ADMIN_COLOR_WIDTH = 25
ADMIN_COLOR_HEIGHT = 25

TRUNCATE_PRODUCT_NAME = 20

HEX_COLOR_PATTERN = '^#{1}[A-Fa-f0-9]{6}$'
HEX_COLOR_ERROR_MESSAGE = (
    'Введите hex color в таком формате #00FF74'
)
