NAME_MAX_LENGTH = 200
COLOR_MAX_LENGTH = 7
SLUG_MAX_LENGTH = 200
MEASUREMENT_UNIT_MAX_LENGTH = 200
MIN_MINUTE_VALUE = 1
MIN_AMOUNT_VALUE = 1
HEX_LENGTH = 6

RECIPE_IMAGE_UPLOAD_TO = 'recipes/images/'

ADMIN_IMAGE_WIDTH = 150
ADMIN_IMAGE_HEIGHT = 150

TRUNCATE_PRODUCT_NAME = 20
