# Generated by Django 3.2.16 on 2024-04-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='is_subscribed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
