# Generated by Django 3.2.16 on 2024-04-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptions_is_subscribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='is_subscribed',
        ),
        migrations.AddConstraint(
            model_name='subscriptions',
            constraint=models.UniqueConstraint(fields=('user', 'subscribing'), name='unique_name_subscribing'),
        ),
    ]
