# Generated by Django 3.2.16 on 2024-05-18 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Введите hex color в таком формате #00FF74', regex='^#{1}[A-Fa-f0-9]{6}$')], verbose_name='Цвет (hex)'),
        ),
    ]
