# Generated by Django 3.2.16 on 2024-04-24 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipeingredientamount_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredientamount',
            options={'ordering': ('recipe', 'ingredient', 'amount'), 'verbose_name': 'Ингредиент и количество', 'verbose_name_plural': 'Ингредиенты и количество'},
        ),
    ]
